name: Publish on Manual Release
on:
  release:
    types: [created]
jobs:
  released:
    runs-on: ubuntu-latest
    if: contains(github.event.release.author.login, 'rentpath-jenkins') == false && contains(github.event.release.author.login, 'rentpath-semantic-release') == false
    steps:
      - name: trigger build
        run: |
          curl --request POST \
               --header "Accept: application/vnd.github.everest-preview+json" \
               --header "Authorization: Bearer ${{ secrets.GH_REPO_DISPATCH_RENTPATH_BOT }}" \
               --url https://api.github.com/repos/${{ github.repository }}/dispatches \
               --data-binary '{"event_type":"semantic-release","client_payload":{"ref":"${{ github.ref }}","sha":"${{ github.sha }}"}}'
