name: Merging
on:
  pull_request:
    types: [closed]
jobs:
  merged:
    if: github.event.pull_request.merged == true
    runs-on: 'ubuntu-latest'
    steps:
      - name: trigger build
        run: |
          curl --request POST \
               --header "Accept: application/vnd.github.everest-preview+json" \
               --header "Authorization: Bearer ${{ secrets.GH_REPO_DISPATCH_RENTPATH_BOT }}" \
               --url "https://api.github.com/repos/${{ github.repository }}/dispatches" \
               --data-binary '{"event_type":"semantic-release","client_payload":{"ref":"${{ github.ref }}","sha":"${{ github.sha }}"}}'
