name: Publish Package
on:
  repository_dispatch:
    types: [semantic-release]
  workflow_dispatch:
    inputs:
      ref:
        description: The ref of the commit to build.
        required: true
jobs:
  publish:
    runs-on: 'ubuntu-latest'
    steps:
      # - name: get rossum app token
      #   id: rossum
      #   uses: getsentry/action-github-app-token@v1
      #   with:
      #     app_id: ${{ secrets.ROSSUM_APP_ID }}
      #     private_key: ${{ secrets.ROSSUM_PRIVATE_KEY }}

      - name: check out most recent commit
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.ref || github.event.client_payload.ref }}
          token: ${{ github.token }}

      - uses: actions/setup-node@v2
        with:
          node-version: '12.x'
          registry-url: 'https://npm.pkg.github.com/'
          scope: '@rentpath'

      - name: install dependencies
        run: |
          yarn config set @rentpath:registry https://npm.pkg.github.com
          yarn install --ignore-scripts
        env:
          NODE_AUTH_TOKEN: ${{ github.token }}

      - name: safely run post-install scripts
        run: npm rebuild && npm run prepare --if-present

      # might be useful in the future
      # - name: build
      #   run: yarn build

      - name: publish
        run: npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ github.token }}
